version: 0.0
os: linux

files:
  - source: /
    destination: /home/herewego
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: script/deploy.sh
      timeout: 60