spring:
  datasource:
    url: jdbc:mysql://localhost:3306/herewego?autoReconnect=true
    username: root
    password: Hwg2022!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    sho-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true

server:
  port: 8080

logging:
  config: classpath:logback-dev.xml
  level:
    root: info
