spring:
  datasource:
    url: jdbc:mysql://localhost:3306/herewego?autoReconnect=true
    username: root
    password: Hwg2022! #TODO: parameter store 저장
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl:
        auto: true
      hbm2ddl:
        auto: true
    generate-ddl: true

server:
  port: 8080

logging:
  config: classpath:logback-dev.xml
  level:
    root: info
