spring:
  profiles:
    active: @spring.profiles.active@

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "187461438837-03155gdchfp1fh060clgm32fe8tkjk0a.apps.googleusercontent.com"
            client-secret: "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"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: profile, email
          github:
            client-id: "db55c913262fcc69405a"
            client-secret: "0f95e6d3b1cc8706f905b96801b5a778a34ba22b"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: user


app:
  auth:
    token:
      secret-key: "6B64DCA4E72F58EDIKU9AAB215FE7"
      refresh-cookie-key: "refresh"
  oauth2:
    authorizedRedirectUri: "http://localhost:8080/health"

server:
  port: 8080

logging:
  level:
    root: info

