name: "0.개발"

on:
  pull_request:
    branches:
      - develop
      - 'feature/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 43.200.211.133
          username: ec2-user
          port: 22
          key: ${{secrets.DEV_SSH_PRIVATE_SECRETS}}
          script: |
            whoami
            ls -al