name: "0.개발"

on:
  pull_request:
    branches:
      - develop
      - 'feature/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      # Caching dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      #connect jumphost with ssh
      - name: connect jumphost with ssh
        run: |
          mkdir ~/.ssh
          echo "${{secrets.DEV_SSH_SECRETS}}" > key
          sudo chmod 600 ./key
          ssh -T -o StrictHostKeyChecking=no -i ./key -L 13306:localhost:3306 ec2-user@43.200.211.133
      # Build
      - name: Build and Test
        run: mvn -Ptest -B package --file pom.xml
      # AWS 인증
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Result
          path: target/surefire-reports/*.xml
          reporter: jest-junit
          fail-on-error: true